services:
  - type: web
    name: interniq
    env: python
    buildCommand: "" # No dependencies to install
    startCommand: "python backend/server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
